#include "Analyzer.h"

// Implement analyzer classes here








// ===========================================================================
// Testing implementation below. Write analyzer logic above these lines.
// ===========================================================================

CSC252::StatisticsAnalyzerTest::~StatisticsAnalyzerTest()
{

}

// GENERATED BY CLAUDE/ANTHROPIC AI - Not required by the assignment.
// These requirement lists are generated by Claude/Anthropic AI to make my life easier because I spent 12 hours on this.
// 
// Requirement coverage, by test number (requirement IDs are from README.md). Every test builds the analyzer
// through an Analyzer pointer and prints all five lines, so STATS-02, STATS-03, STATS-09 and STATS-10 are
// exercised by every case and are only listed where a case is aimed at them.
//   00 Odd Count Unsorted       STATS-01, STATS-04
//   01 Even Median Exact        STATS-05
//   02 Even Median Remainder    STATS-05 (the mean of the two middle values is truncated)
//   03 Single Element           STATS-04, STATS-11
//   04 Two Equal Elements       STATS-05, STATS-06
//   05 All Same                 STATS-06
//   06 Mode Tie First Wins      STATS-07
//   07 Mode At End              STATS-08
//   08 Mode At Start            STATS-06
//   09 Mode Three Way Tie       STATS-01, STATS-07
//   10 Negatives And Zero       STATS-02, STATS-03, QA-02
//   11 Largest Ints             STATS-05, QA-02 (adding two INT_MAX values must not overflow)
//   12 Smallest And Largest     STATS-02, STATS-03, STATS-05, QA-02
//   13 Empty Array              STATS-11, STATS-12
//   14 Null Array Throws        QA-02 (throws on invalid input, per the README coding convention)
//   15 Null Size Zero           STATS-11, STATS-12 (empty data is valid)
//   16 All Unique Mode          STATS-06, STATS-07

/**
 * @brief Executes a test case to validate StatisticsAnalyzer.
 *
 * See the class comment in Analyzer.h for the input format.
 *
 * @param Input The input stream containing one statistics test case.
 * @param Output The output stream to write the analyzer's result to.
 *
 * @throws std::runtime_error If the test case itself is malformed. That is a mistake in the test file,
 *         not a result from the analyzer, so it is reported as a test error.
 */
void CSC252::StatisticsAnalyzerTest::Execute(std::istream& Input, std::ostream& Output)
{
    // Explicitly allows us to catch test cases that expect an exception
    // i.e.: "This test makes sure an exception is thrown by the analyzer"
    Input >> std::ws;
    const int FirstCharacter = Input.peek(); // read the first character without consuming it
    if (FirstCharacter == 'e')
    {
        this->ExpectsThrowCase(Input, Output);
        return;
    }

    // Expected Exception handled. Any exception hereafter is unexpected and a test case error.

    vector<int> Values;
    int Value;
    while (Input >> Value)
        Values.push_back(Value);
    if (!Input.eof())
        throw std::runtime_error("Input contained non-integer value(s)");

    int Spare{0};
    std::unique_ptr<Analyzer> AnalyzerObject =
        std::make_unique<StatisticsAnalyzer>(Values.empty() ? &Spare : Values.data(), static_cast<int>(Values.size()));
    
    Output << AnalyzerObject->analyze();
}

bool CSC252::StatisticsAnalyzerTest::Compare(const string& Expected, const string& Actual, TestResult& OutResult)
{
    if (TestObject::Compare(Expected, Actual, OutResult))
        return true;

    OutResult.Message = "Expected '" + Expected + "' but got '" + Actual + "'";
    return false;
}

void CSC252::StatisticsAnalyzerTest::ExpectsThrowCase(std::istream& Input, std::ostream& Output)
{
    char Action{'x'};
    int Size{-1};
    if (!(Input >> Action >> Size)) // test case input incorrect
        throw std::runtime_error("Throw test input must start with e and a size");

    try // the try case is expected to throw an exception
    {
        StatisticsAnalyzer AnalyzerObject(nullptr, Size);
        Output << AnalyzerObject.analyze();
    }
    catch (const std::invalid_argument&)
    {
        Output << "invalid_argument";
    }
    catch (const std::exception&)
    {
        Output << "exception";
    }
}

CSC252::SearchAnalyzerTest::~SearchAnalyzerTest()
{

}

// GENERATED BY CLAUDE/ANTHROPIC AI - Not required by the assignment.
// These requirement lists are generated by Claude/Anthropic AI to make my life easier because I spent 12 hours on this.
// 
// Requirement coverage, by test number (requirement IDs are from README.md). Every test builds the analyzer
// through an Analyzer pointer, so SA-01 and SA-03 are exercised by all of them.
//   00 All Found          SA-02, SA-05, SA-06, SA-07, SA-08 (unsorted data holding every value 0-999)
//   01 None Found         SA-07, SA-08
//   02 Empty Array        SA-07, SA-08, QA-02
//   03 Count Resets       SA-09
//   04 Null Array Throws  QA-02 (throws on invalid input, per the README coding convention)
//   05 Null Size Zero     QA-02 (null with size 0 is valid)
// SA-04 (exactly 100 searches) is only partly visible: "All Found" expects exactly 100 found. SA-05's endpoints
// (0 and 999 individually) are not tested, since that needs many repeated calls.

/**
 * @brief Executes a test case to validate SearchAnalyzer.
 *
 * See the class comment in Analyzer.h for the modes.
 *
 * @param Input The input stream containing one search analyzer test case.
 * @param Output The output stream to write the result to.
 *
 * @throws std::runtime_error If the test case itself is malformed. That is a mistake in the test file,
 *         not a result from the analyzer, so it is reported as a test error.
 */
void CSC252::SearchAnalyzerTest::Execute(std::istream& Input, std::ostream& Output)
{
    string ActionWord;
    if (!(Input >> ActionWord))
        throw std::runtime_error("Test must start with an action word");

    if (ActionWord == "null")
    {
        this->ExpectsThrowCase(Input, Output);
        return;
    }

    // Expected Exception handled. Any exception hereafter is unexpected and a test case error.
    const bool bScrambledData = ActionWord == "all" || ActionWord == "reset";
    const bool bFileData = ActionWord == "none";

    vector<int> Values{};
    if (bScrambledData)
    {
        // Generates random values as specified by the instructions
        for (int Index = 0; Index < 1000; Index++)
            Values.push_back(999-Index); // Reverses the order of the values, ensuring it's not ordered.
    }

    else if (bFileData)
    {
        int Value;
        while (Input >> Value)
            Values.push_back(Value);
        
        if (!Input.eof())
            throw std::runtime_error("Input contained non-integer value(s)");
    }

    else
        throw std::runtime_error("Unknown ActionWord: " + ActionWord);

    int Spare{0};
    std::unique_ptr<Analyzer> AnalyzerObject =
        std::make_unique<SearchAnalyzer>(Values.empty() ? &Spare : Values.data(), static_cast<int>(Values.size()));

    // 'reset' tests SA-09: Repeated calls are different counts
    if (ActionWord == "reset")
    {
        const string FirstAnswer = AnalyzerObject->analyze();
        Output << FirstAnswer << "\n" << AnalyzerObject->analyze();
        return;
    }

    Output << AnalyzerObject->analyze();
}

bool CSC252::SearchAnalyzerTest::Compare(const string& Expected, const string& Actual, TestResult& OutResult)
{
    if (TestObject::Compare(Expected, Actual, OutResult))
        return true;

    OutResult.Message = "Expected '" + Expected + "' but got '" + Actual + "'";
    return false;
}

void CSC252::SearchAnalyzerTest::ExpectsThrowCase(std::istream& Input, std::ostream& Output)
{
    int Size{-1};
    if (!(Input >> Size)) // test case input incorrect
        throw std::runtime_error("Throw test input must give a size after 'null'");

    try // the try case is expected to throw an exception
    {
        SearchAnalyzer AnalyzerObject(nullptr, Size);
        Output << AnalyzerObject.analyze();
    }
    catch (const std::invalid_argument&)
    {
        Output << "invalid_argument";
    }
    catch (const std::exception&)
    {
        Output << "exception";
    }
}
