
#include "BinarySearch.h"

// Implement binary search here
bool binary_search_recursive(int* values, int key, int start, int end)
{
    return false;
}

bool binary_search(int* values, int key, int size)
{
    return false;
}


// ===========================================================================
// Testing implementation below. Write binary search logic above these lines.
// ===========================================================================

CSC252::BinarySearchTest::~BinarySearchTest()
{

}

// GENERATED BY CLAUDE/ANTHROPIC AI - Not required by the assignment.
// These requirement lists are generated by Claude/Anthropic AI to make my life easier because I spent 12 hours on this.
// 
// Requirement coverage, by test number (requirement IDs are from README.md). Every test calls through the
// required signatures (SEARCH-01, SEARCH-02), so those are only listed where a test is aimed at them.
//   00 Middle Value             SEARCH-06
//   01 First Value              SEARCH-06
//   02 Last Value               SEARCH-06
//   03 Between Values           SEARCH-07
//   04 Below Smallest           SEARCH-07
//   05 Above Largest            SEARCH-07
//   06 Single Element Found     SEARCH-09
//   07 Single Element Missing   SEARCH-09, SEARCH-07
//   08 Duplicates Found         SEARCH-08
//   09 All Same Found           SEARCH-08
//   10 All Same Missing         SEARCH-08, SEARCH-07
//   11 Even Count Found         SEARCH-06, QA-02
//   12 Two Elements Second      SEARCH-06, QA-02
//   13 Empty Array              SEARCH-05, QA-02 (an empty range stops the search)
//   14 Smallest Int             SEARCH-06, QA-02
//   15 Largest Int              SEARCH-06, QA-02
//   16 Range Whole Array        SEARCH-02, SEARCH-04
//   17 Range Excludes Match     SEARCH-02, SEARCH-04 (only the given range is searched)
//   18 Range Single Index       SEARCH-02, SEARCH-05
//   19 Range Empty              SEARCH-02, SEARCH-05
//   20 Null Array Throws        QA-02 (throws on invalid input, per the README coding convention)
//   21 Negative Size Throws     QA-02 (throws on invalid input)
//   22 Null Size Zero           QA-02 (null with size 0 is valid)
//   23 Range Null Throws        QA-02, SEARCH-02 (throws on invalid input)
//   24 Range Negative Start     QA-02, SEARCH-02 (throws on invalid input)
//   25 Range Null Empty         QA-02, SEARCH-05 (an empty range never touches the array)
//   26 Second Value             SEARCH-06
//   27 Left Of Middle           SEARCH-06
//   28 Right Of Middle          SEARCH-06
//   29 Second To Last           SEARCH-06
// SEARCH-03 (binary_search calls binary_search_recursive) and SEARCH-04's "a smaller portion on each call" can't
// be seen from the answers alone, so code review checks them.

/**
 * @brief Executes a test case to validate binary_search and binary_search_recursive.
 *
 * See the class comment in BinarySearch.h for the input format.
 *
 * @param Input The input stream containing one search test case.
 * @param Output The output stream to write "true", "false", "invalid_argument" or "exception".
 *
 * @throws std::runtime_error If the test case itself is malformed. That is a mistake in the test file,
 *         not a result from the search, so it is reported as a test error.
 */
void CSC252::BinarySearchTest::Execute(std::istream& Input, std::ostream& Output)
{
    // A leading letter selects the mode. A number (or '-') means a plain binary_search over a real array.
    Input >> std::ws;
    char Action{'h'};
    const int First = Input.peek();
    if (First == 'e' || First == 'E' || First == 'r' || First == 'n')
        Input >> Action;

    const bool bUsesNullArray = Action == 'e' || Action == 'n';
    const bool bUsesRange = Action == 'r' || Action == 'n';
    const bool bUsesDeclaredSize = Action == 'e' || Action == 'E';

    int Key{0};
    int Start{0};
    int End{-1};
    int Size{0};
    if (!(Input >> Key))
        throw std::runtime_error("Search test input must contain a key");
    if (bUsesDeclaredSize && !(Input >> Size))
        throw std::runtime_error("Search test input must contain a size after the key");
    if (bUsesRange && !(Input >> Start >> End))
        throw std::runtime_error("Search test input must contain a start and end index after the key");

    vector<int> Values;
    if (!bUsesNullArray)
    {
        int Value;
        while (Input >> Value)
            Values.push_back(Value);

        if (!Input.eof())
            throw std::runtime_error("Input contained non-integer value(s)");
    }

    if (Action == 'h')
        Size = static_cast<int>(Values.size());

    // A range or size that reaches past the values would make the search read past the array. That is a mistake in
    // the test file, not in the search, so it is reported as a test error. (Negative values are deliberately allowed
    // through, since rejecting them is the search's job.)
    if (Action == 'E' && Size >= 0 && static_cast<size_t>(Size) > Values.size())
        throw std::runtime_error("Search test declares a size larger than its values");
    if (Action == 'r' && Start >= 0 && Start <= End && static_cast<size_t>(End) >= Values.size())
        throw std::runtime_error("Search test range ends past its values");

    // A real pointer is passed even for an empty array, because an empty vector's data() may be null,
    // which would turn "valid empty array" into the same case as "null array".
    int Placeholder{0};
    int* Data = nullptr;
    if (!bUsesNullArray)
    {
        Data = &Placeholder;
        if (!Values.empty())
            Data = Values.data();
    }

    try // the call under test may throw. What it throws is the result.
    {
        bool bFound;
        if (bUsesRange)
            bFound = binary_search_recursive(Data, Key, Start, End);
        else
            bFound = binary_search(Data, Key, Size);

        Output << (bFound ? "true" : "false");
    }
    catch (const std::invalid_argument&)
    {
        Output << "invalid_argument";
    }
    catch (const std::exception&)
    {
        Output << "exception";
    }
    catch (...)
    {
        throw std::runtime_error("Unexpected exception");
    }
}

bool CSC252::BinarySearchTest::Compare(const string& Expected, const string& Actual, TestResult& OutResult)
{
    // Only the four result words are allowed. Anything else is a typo in a .out file, not a result.
    const bool bValidTrue = Expected == "true";
    const bool bValidFalse = Expected == "false";
    const bool bInvalidArg = Expected == "invalid_argument";
    const bool bException = Expected == "exception";
    if (!(bValidTrue || bValidFalse || bInvalidArg || bException))
        throw std::runtime_error("Expected output must be true, false, invalid_argument or exception");

    if (TestObject::Compare(Expected, Actual, OutResult))
        return true;

    OutResult.Message = "Expected '" + Expected + "' but got '" + Actual + "'";
    return false;
}
