/**
 * @file    CSC252-Assignment-5.cpp
 * @authors Melanie Harris, ...
 * @date    05 OCT 2026
 * @version 0.1
 * @brief   Implementation and main driver for the Statistical Analysis assignment.
 * 
 * @license MIT
 */

// Color helpers
// NOTE: AI-Generated code for color support. Not required by the assignment.
// ========== START CLAUDE GENERATED CODE ==========
#ifdef _WIN32
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <io.h>
#else
#include <unistd.h>
#endif
// ========== END CLAUDE GENERATED CODE ==========

// Assignment includes and usings.
#include "SelectionSort.h"
#include <iomanip>
using CSC252::SelectionSort;
using CSC252::SelectionSortTest;
using std::cout;
using std::endl;

// =============== HELPER FUNCTIONS ==================
namespace Helpers
{
    // Allows easy printing to the console with cout and newline already handled.
    static void print_console(const string& message) {cout << message << "\n";}
    
    // https://en.cppreference.com/cpp/utility/functional/invoke
    // Dynamic handling of a function to see if it throws an exception.
    template <typename Func, typename... Args>
    static bool Throws(Func&& FunctionCall, Args&&... Arguments)
    {
        try
            { std::invoke(std::forward<Func>(FunctionCall), std::forward<Args>(Arguments)...); }
        catch (const std::exception&)
            { return true; }
        return false;
    }
    
    // Implemented as a deeper version of the above dynamic handler, to see if the exception is what we expected to get.
    template <typename ExpectedException, typename Func, typename... Args>
    static bool ExpectThrow(Func&& FunctionCall, Args&&... Arguments)
    {
        try
            { std::invoke(std::forward<Func>(FunctionCall), std::forward<Args>(Arguments)...); }
        catch (const ExpectedException&)
            { return true; }
        return false;
    }
    
    // =============== START CLAUDE GENERATED CODE ==================
    // code generated by Claude
    // TODO - Remove before submission. Colors are for us, not for the assignment.
    static bool bUseColor = false; static bool enable_color() {
#ifdef _WIN32
        const HANDLE Console = GetStdHandle(STD_OUTPUT_HANDLE); DWORD Mode = 0; if (Console == INVALID_HANDLE_VALUE || !GetConsoleMode(Console, &Mode)) { return false; } return SetConsoleMode(Console, Mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING) != 0;
#else
        return isatty(STDOUT_FILENO) != 0;
#endif
    } static string colorize(const string& text, const char* color) { if (!bUseColor) { return text; } return string(color) + text + "\x1b[0m"; } constexpr const char* Lime = "\x1b[92m"; constexpr const char* Yellow = "\x1b[93m"; constexpr const char* Red = "\x1b[91m";
    // ================= END CLAUDE GENERATED CODE ====================
}
// ======== END HELPERS ========

namespace
{
    const vector<string> TestDescriptions =
    {
        "Shuffle Test", "Shuffled Permutation", "Empty Array", "Single Element", "Already Sorted",
        "Reverse Sorted", "Same Value", "Mixed Duplicates", "Negatives & Extremes", "Two Elements",
        "Null Pointer Throw", "Negative Size Throw", "Null Size Zero", "Valid Array", "Empty Array"
    };
    
    string FormatTestFile(const size_t TestNumber)
    {
        if (TestNumber < 10)
        {
            std::ostringstream TestLabel;
            TestLabel << std::setw(2) << std::setfill('0') << TestNumber;
            return TestLabel.str();
        }
        return std::to_string(TestNumber);
    }
    
    string TestDescription(const size_t TestNumber)
    {
        std::ostringstream TestLabel;
        TestLabel << "Test " << std::setw(2) << std::setfill('0')
                  << TestNumber << " (" << TestDescriptions[TestNumber] << ")";
        return TestLabel.str();
    }
    
}

int main()
{
    // TODO - Remove before submission. This AI-generated code is just to make testing easier.
    // ===== AI GENERATED CODE - ONLY FOR DEVELOPMENT AND TESTING =====
    Helpers::bUseColor = Helpers::enable_color();
    const char* ColorLime = Helpers::Lime;
    const char* ColorYellow = Helpers::Yellow;
    const char* ColorRed = Helpers::Red;
    // ===== END AI GENERATED CODE =====
    
    
    // =================== START SELECTION SORT TESTS ==================================
    Helpers::print_console("Beginning Selection Sort Tests...");
    
    // unique_ptr: Handles garbage collection when scope is lost.
    // source: https://en.cppreference.com/cpp/memory/unique_ptr
    vector<std::unique_ptr<SelectionSortTest>> SelectionSortTests;
    
    // future: The value doesn't exist now, but will after async is complete.
    // source: https://en.cppreference.com/cpp/thread/future
    vector<std::future<bool>> SelectionSortTestFutures;
    
    const int NumDescriptions = static_cast<int>(TestDescriptions.size());
    for (int TestNumber = 0; TestNumber < NumDescriptions; TestNumber++)
    {
        auto TestObject = std::make_unique<SelectionSortTest>(TestNumber); // creates an object via smart pointers
        TestObject->SetInputFile("tests/" + FormatTestFile(TestNumber) + ".in");
        TestObject->SetOutputFile("tests/" + FormatTestFile(TestNumber) + ".out");
        SelectionSortTestFutures.push_back(TestObject->RunAsync()); // runs the test in a worker thread
        
        // IDE recommended "std::move"... Had to research it; Source: https://en.cppreference.com/cpp/utility/move
        // Turns out that std::move is used to move from its original source to the new object.
        SelectionSortTests.push_back(std::move(TestObject)); // keeps track of the test as it runs
    }
    
    size_t TestsFailed = 0;
    
    // Waits for each test to complete and then prints their result.
    for (size_t TestNumber = 0; TestNumber < SelectionSortTests.size(); TestNumber++)
    {
        SelectionSortTestFutures[TestNumber].get();
        const TestResult Result = SelectionSortTests[TestNumber]->GetResult();
        
        if (Result.State == TestState::Passed)
        {
            // TODO - Switch colored response out for test pass result when testing is done.
            //Helpers::print_console(TestDescription(TestNumber) + ": Passed.");
            Helpers::print_console(TestDescription(TestNumber) + ": " + Helpers::colorize("Passed", ColorLime) + ".");
            continue; // Move to next test
        }
        
        TestsFailed++;
        if (Result.State == TestState::Error)
        {
            // TODO - Switch colored response out for test pass result when testing is done.
            //Helpers::print_console(TestDescription(TestNumber) + ": Errored. Reason: " + Result.Message);
            Helpers::print_console(TestDescription(TestNumber) + ": " + Helpers::colorize("Error", ColorRed) + ". Reason: " + Result.Message);
            continue;
        }

        // TODO - Switch colored response out for test pass result when testing is done.
        //Helpers::print_console(TestDescription(TestNumber) + ": Failed. " + Result.Message);
        Helpers::print_console(TestDescription(TestNumber) + ": " + Helpers::colorize("Failed", ColorYellow) + ". Reason: " + Result.Message);
    }
    
    Helpers::print_console("Selection Sort Tests Complete.");
    // ===================== END SELECTION SORT TESTS ================================
    
    Helpers::print_console("  All Tests Complete... " + std::to_string(TestsFailed) + " tests failed.");
}

