/**
 * @file    CSC252-Assignment-5.cpp
 * @authors Melanie Harris, ...
 * @date    05 OCT 2026
 * @version 0.1
 * @brief   Implementation and main driver for the Statistical Analysis assignment.
 * 
 * @license MIT
 */

// Color helpers
// NOTE: AI-Generated code for color support. Not required by the assignment.
// ========== START CLAUDE GENERATED CODE ==========
#include "Analyzer.h"
#include "BinarySearch.h"
#ifdef _WIN32
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <io.h>
#else
#include <unistd.h>
#endif
// ========== END CLAUDE GENERATED CODE ==========

// Assignment includes and usings.
#include "SelectionSort.h"
#include <iomanip>
using CSC252::BinarySearchTest;
using CSC252::SelectionSortTest;
using CSC252::StatisticsAnalyzerTest;
using CSC252::SearchAnalyzerTest;
using std::cout;
using std::endl;

// statics; Defines one string in one place.
#define TEST_DIR "tests/"
#define TEST_SELECTION_DIR "selection/"
#define TEST_BINARY_DIR "search/"
#define TEST_SEARCHANALYZER_DIR "searchanalyzer/"
#define TEST_STATISTICS_DIR "statistics/"
#define TITLE_SELECTIONSORT "Selection Sort"
#define TITLE_BINARYSEARCH "Binary Search"
#define TITLE_STATISTICS "Statistics Analyzer"
#define TITLE_SEARCHANALYZER "Search Analyzer"

// =============== HELPER FUNCTIONS ==================
namespace Helpers
{
    // Allows easy printing to the console with cout and newline already handled.
    static void print_console(const string& message) {cout << message << "\n";}
    
    // https://en.cppreference.com/cpp/utility/functional/invoke
    // Dynamic handling of a function to see if it throws an exception.
    template <typename Func, typename... Args>
    static bool Throws(Func&& FunctionCall, Args&&... Arguments)
    {
        try
            { std::invoke(std::forward<Func>(FunctionCall), std::forward<Args>(Arguments)...); }
        catch (const std::exception&)
            { return true; }
        return false;
    }
    
    // Implemented as a deeper version of the above dynamic handler, to see if the exception is what we expected to get.
    template <typename ExpectedException, typename Func, typename... Args>
    static bool ExpectThrow(Func&& FunctionCall, Args&&... Arguments)
    {
        try
            { std::invoke(std::forward<Func>(FunctionCall), std::forward<Args>(Arguments)...); }
        catch (const ExpectedException&)
            { return true; }
        return false;
    }
    
    // =============== START CLAUDE GENERATED CODE ==================
    // code generated by Claude
    // TODO - Remove before submission. Colors are for us, not for the assignment.
    static bool bUseColor = false; static bool enable_color() {
#ifdef _WIN32
        const HANDLE Console = GetStdHandle(STD_OUTPUT_HANDLE); DWORD Mode = 0; if (Console == INVALID_HANDLE_VALUE || !GetConsoleMode(Console, &Mode)) { return false; } return SetConsoleMode(Console, Mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING) != 0;
#else
        return isatty(STDOUT_FILENO) != 0;
#endif
    } static string colorize(const string& text, const char* color) { if (!bUseColor) { return text; } return string(color) + text + "\x1b[0m"; } constexpr const char* Lime = "\x1b[92m"; constexpr const char* Yellow = "\x1b[93m"; constexpr const char* Red = "\x1b[91m";
    // ================= END CLAUDE GENERATED CODE ====================
}
// ======== END HELPERS ========

namespace Tests
{
    const vector<string> SortTestDescriptions =
    {
        "Shuffle Test", "Shuffled Permutation", "Empty Array", "Single Element", "Already Sorted",
        "Reverse Sorted", "Same Value", "Mixed Duplicates", "Negatives & Extremes", "Two Elements",
        "Null Pointer Throw", "Negative Size Throw", "Null Size Zero", "Valid Array",
        "Empty; Valid Pointer"
    };
    
    const vector<string> SearchTestDescriptions = 
    {
        "Middle Value", "First Value", "Last Value", "Between Values", "Below Smallest",
        "Above Largest", "Single Element Found", "Single Element Missing", "Duplicates Found",
        "All Same Found", "All Same Missing", "Even Count Found", "Two Elements Second", "Empty Array",
        "Smallest Int", "Largest Int", "Range Whole Array", "Range Excludes Match", "Range Single Index",
        "Range Empty", "Null Array Throws", "Negative Size Throws", "Null Size Zero",
        "Range Null Throws", "Range Negative Start", "Range Null Empty", "Second Value",
        "Left Of Middle", "Right Of Middle", "Second To Last"
    };
    
    const vector<string> StatisticsTestDescriptions =
        {
        "Odd Count Unsorted", "Even Median Exact", "Even Median Remainder", "Single Element", "Two Equal Elements",
        "All Same", "Mode Tie First Wins", "Mode At End", "Mode At Start", "Mode Three Way Tie",
        "Negatives And Zero", "Largest Ints", "Smallest And Largest", "Empty Array", "Null Array Throws",
        "Null Size Zero", "All Unique Mode"
    };
    
    const vector<string> AnalyzerTestDescriptions =
    {
        "All Found", "None Found", "Empty Array", "Count Resets", "Null Array Throws", "Null Size Zero"
    };
    
    string FormatTestFile(const size_t TestNumber)
    {
        if (TestNumber < 10)
        {
            std::ostringstream TestLabel;
            TestLabel << std::setw(2) << std::setfill('0') << TestNumber;
            return TestLabel.str();
        }
        return std::to_string(TestNumber);
    }
    
    string TestDescription(const size_t TestNumber, const vector<string>& TestDescription)
    {
        std::ostringstream TestLabel;
        TestLabel << "Test " << std::setw(2) << std::setfill('0')
                  << TestNumber << " (" << TestDescription[TestNumber] << ")";
        return TestLabel.str();
    }
    
    /**
     * @brief A polymorphic method that can be used to run tests for any type of test object.
     * Once I started making the tests for Binary Search, I realized most of the test logic was rinse and repeat.
     * This method is a template that can be used to run tests for any type of test object.
     * 
     * @tparam TestType The test object type
     * @param TestTitle The title of the test group (i.e. Selection Sort)
     * @param TestDescriptions The descriptions of each test (i.e. "Test 01 (20 shuffled numbers)")
     * @return The number of tests failed.
     */
    template <typename TestType>
    int RunTests(const string& TestTitle, const vector<string>& TestDescriptions)
    {
        // TODO - Remove before submission. This AI-generated code is just to make testing easier.
        // ===== AI GENERATED CODE - ONLY FOR DEVELOPMENT AND TESTING =====
        Helpers::bUseColor = Helpers::enable_color();
        const char* ColorYellow = Helpers::Yellow;
        const char* ColorRed = Helpers::Red;
        // ===== END AI GENERATED CODE =====
        
        int TestsFailed{0};
        string TestDirectory{TEST_DIR};
        if (TestTitle == TITLE_SELECTIONSORT)
            TestDirectory += TEST_SELECTION_DIR;
        else if (TestTitle == TITLE_BINARYSEARCH)
            TestDirectory += TEST_BINARY_DIR;
        else if (TestTitle == TITLE_STATISTICS)
            TestDirectory += TEST_STATISTICS_DIR;
        else if (TestTitle == TITLE_SEARCHANALYZER)
            TestDirectory += TEST_SEARCHANALYZER_DIR;
        
        // unique_ptr: Handles garbage collection when scope is lost.
        // source: https://en.cppreference.com/cpp/memory/unique_ptr
        vector<std::unique_ptr<TestType>> SelectionSortTests;
    
        // future: The value doesn't exist now, but will after async is complete.
        // source: https://en.cppreference.com/cpp/thread/future
        vector<std::future<bool>> SelectionSortTestFutures;
        
        const int NumDescriptions = static_cast<int>(TestDescriptions.size());
        for (int TestNumber = 0; TestNumber < NumDescriptions; TestNumber++)
        {
            auto SortTestObject = std::make_unique<TestType>(TestNumber); // creates an object via smart pointers
            SortTestObject->SetInputFile(TestDirectory + FormatTestFile(TestNumber) + ".in");
            SortTestObject->SetOutputFile(TestDirectory + FormatTestFile(TestNumber) + ".out");
            SelectionSortTestFutures.push_back(SortTestObject->RunAsync()); // runs the test in a worker thread
        
            // IDE recommended "std::move"... Had to research it; Source: https://en.cppreference.com/cpp/utility/move
            // Turns out that std::move is used to move from its original source to the new object.
            SelectionSortTests.push_back(std::move(SortTestObject)); // keeps track of the test as it runs
        }
        
        for (size_t TestNumber = 0; TestNumber < SelectionSortTests.size(); TestNumber++)
        {
            SelectionSortTestFutures[TestNumber].get();
            const TestResult Result = SelectionSortTests[TestNumber]->GetResult();
        
            // Passed tests are silent. Only failures and errors are printed.
            if (Result.State == TestState::Passed)
                continue; // Move to next test
        
            TestsFailed++;
            if (Result.State == TestState::Error)
            {
                // TODO - Switch colored response out for test pass result when testing is done.
                //Helpers::print_console(TestDescription(TestNumber) + ": Errored. Reason: " + Result.Message);
                Helpers::print_console(TestDescription(TestNumber, TestDescriptions) + ": " 
                    + Helpers::colorize("Error", ColorRed) + ". Reason: " + Result.Message);
                continue;
            }

            // TODO - Switch colored response out for test pass result when testing is done.
            //Helpers::print_console(TestDescription(TestNumber) + ": Failed. " + Result.Message);
            Helpers::print_console(TestDescription(TestNumber, TestDescriptions) + ": " 
                + Helpers::colorize("Failed", ColorYellow) + ". Reason: " + Result.Message);
        }
        return TestsFailed;
    }
}

int main()
{
#ifdef _DEBUG
    int TestsFailed = 0;
    
    Helpers::print_console("  ==== SELECTION SORT ====");
    TestsFailed += Tests::RunTests<SelectionSortTest>(TITLE_SELECTIONSORT, Tests::SortTestDescriptions);
    
    Helpers::print_console("  ==== BINARY SEARCH ====");
    TestsFailed += Tests::RunTests<BinarySearchTest>(TITLE_BINARYSEARCH, Tests::SearchTestDescriptions);
    
    Helpers::print_console("  ==== STATS ANALYZER ====");
    TestsFailed += Tests::RunTests<StatisticsAnalyzerTest>(TITLE_STATISTICS, Tests::StatisticsTestDescriptions);
    
    Helpers::print_console("  ==== SEARCH ANALYZER ====");
    TestsFailed += Tests::RunTests<SearchAnalyzerTest>(TITLE_SEARCHANALYZER, Tests::AnalyzerTestDescriptions);
    
    // Waits for each test to complete and then prints their result.
    const size_t TotalTests = Tests::SortTestDescriptions.size()
                            + Tests::SearchTestDescriptions.size()
                            + Tests::StatisticsTestDescriptions.size()
                            + Tests::AnalyzerTestDescriptions.size();
    
    if (TestsFailed > 0)
    {
        Helpers::print_console("  All Tests Complete... " 
                                + std::to_string(TestsFailed) + "/" 
                                + std::to_string(TotalTests) + " tests failed.");
    }
    else
        Helpers::print_console("  All Tests Complete. All " + std::to_string(TotalTests) + " tests passed.");
    
    return TestsFailed == 0 ? EXIT_SUCCESS : EXIT_FAILURE;
#else
    // TODO - Actual production output
#endif
}

